### ISSUE TITLE
error when burning the bootloader for avr128DA28 and arduino uno as updi

### ISSUE THREAD

**Issue by hoka83** [SpenceKonde/DxCore#526] opened 2024-04-24 21:32 UTC
![IMG_6061 (1)](https://github.com/SpenceKonde/DxCore/assets/105120867/014d6b0c-0d0e-493b-a0c9-a42e3f5f97a2)
![IMG_6060](https://github.com/SpenceKonde/DxCore/assets/105120867/793d8043-dc7f-42c2-883d-53d0d304b4c4)

**Comment by hoka83** [comment] 2024-04-24 21:33
why it gives me this error? 

avrdude: jtagmkII_initialize(): Cannot locate "flash" and "boot" memories in description
avrdude: jtagmkII_program_enable(): bad response to enter progmode command: RSP_ILLEGAL_MCU_STATE
avrdude: jtagmkII_program_enable(): bad response to enter progmode command: RSP_ILLEGAL_MCU_STATE
avrdude: jtagmkII_read_byte(): bad response to read memory command: RSP_ILLEGAL_MCU_STATE
avr_read(): error reading address 0x0000
read operation not supported for memory "signature"
avrdude: error reading signature data for part "AVR128DA28", rc=-2
avrdude: error reading signature data, rc=-2
avrdude: jtagmkII_program_disable(): bad response to leave progmode command: RSP_ILLEGAL_MCU_STATE
Error while burning bootloader.

**Comment by mikrocoder** [comment] 2024-05-17 16:29
Hi,

Why are you photographing your monitor?
Can't you take screenshots?

About your problem.
The selected com port is wrong.
The Arduino Uno is not an AVR128DA28.
Do you already have the bootloader on it?

**Comment by SpenceKonde** [comment] 2024-07-28 20:30
They have no communication whatsoever between the arduino uno acting as UPDI device and the UPDI device. Wiring incorrect.

**Comment by nomakewan** [comment] 2024-07-29 09:08
Agreed. Suggest closing this as a duplicate of #525 honestly.

**Comment by SpenceKonde** [comment] 2024-09-27 18:15
Though, it should be noted that there were also buggy versions of jtag2updi

**Closed by SpenceKonde** 2024-09-27 18:15 UTC
